# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv0003
# spec:
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   storageClassName: managed
